disabled_rules: # rule identifiers to exclude from running
- force_cast
- force_try
- line_length
- colon
- identifier_name
- cyclomatic_complexity
- trailing_whitespace
- opening_brace
- multiple_closures_with_trailing_closure
- generic_type_name
